(module

  ;; ─── Constants (f32) ───────────────────────────────────────────────────────
  (global $PI (export "PI") f32 (f32.const 3.14159265))
  (global $TWO_PI (export "TWO_PI") f32 (f32.const 6.28318530))
  (global $HALF_PI (export "HALF_PI") f32 (f32.const 1.57079632))
  (global $E (export "E") f32 (f32.const 2.71828182))

  ;; ─── Tier 1 (opcodes) ─────────────────────────────────────────────────────
  (func $sqrt (export "sqrt") (param $x f32) (result f32)
    (f32.sqrt (local.get $x))
  )
  (func $abs_f32 (export "abs_f32") (param $x f32) (result f32)
    (f32.abs (local.get $x))
  )
  (func $abs_i32 (export "abs_i32") (param $x i32) (result i32)
    (local $t i32)
    (local.set $t (i32.shr_s (local.get $x) (i32.const 31)))
    (i32.sub (i32.xor (local.get $x) (local.get $t)) (local.get $t))
  )
  (func $floor (export "floor") (param $x f32) (result f32)
    (f32.floor (local.get $x))
  )
  (func $ceil (export "ceil") (param $x f32) (result f32)
    (f32.ceil (local.get $x))
  )
  (func $round (export "round") (param $x f32) (result f32)
    (f32.nearest (local.get $x))
  )
  (func $trunc (export "trunc") (param $x f32) (result f32)
    (f32.trunc (local.get $x))
  )
  (func $copysign (export "copysign") (param $x f32) (param $y f32) (result f32)
    (f32.copysign (local.get $x) (local.get $y))
  )

  (func $sqrt_f64 (export "sqrt_f64") (param $x f64) (result f64)
    (f64.sqrt (local.get $x))
  )
  (func $abs_f64 (export "abs_f64") (param $x f64) (result f64)
    (f64.abs (local.get $x))
  )
  (func $floor_f64 (export "floor_f64") (param $x f64) (result f64)
    (f64.floor (local.get $x))
  )
  (func $ceil_f64 (export "ceil_f64") (param $x f64) (result f64)
    (f64.ceil (local.get $x))
  )
  (func $round_f64 (export "round_f64") (param $x f64) (result f64)
    (f64.nearest (local.get $x))
  )
  (func $trunc_f64 (export "trunc_f64") (param $x f64) (result f64)
    (f64.trunc (local.get $x))
  )
  (func $copysign_f64 (export "copysign_f64") (param $x f64) (param $y f64) (result f64)
    (f64.copysign (local.get $x) (local.get $y))
  )

  ;; ─── Tier 2 helpers ──────────────────────────────────────────────────────
  ;; sin on [-PI, PI] — Horner form of Taylor terms up to x^7
  ;; Horner: ((-x^2/5040 + 1/120)*x^2 - 1/6)*x^2 + 1
  (func $__sin_reduced (param $x f32) (result f32)
    (local $x2 f32)
    (local $a f32)
    (local $b f32)
    (local $s f32)
    (local.set $x2 (f32.mul (local.get $x) (local.get $x)))
    (local.set $a (f32.add (f32.const 0.008333333) (f32.mul (f32.const -0.0001984127) (local.get $x2))))
    (local.set $b (f32.sub (f32.mul (local.get $a) (local.get $x2)) (f32.const 0.16666667)))
    (local.set $s (f32.add (f32.const 1.0) (f32.mul (local.get $b) (local.get $x2))))
    (f32.mul (local.get $x) (local.get $s))
  )

  (func $__atan_small (param $u f32) (result f32)
    (f32.div
      (local.get $u)
      (f32.add (f32.const 1.0) (f32.mul (f32.const 0.28) (f32.mul (local.get $u) (local.get $u))))
    )
  )

  (func $__atan_full (param $t f32) (result f32)
    (local $u f32)
    (local $one f32)
    (local $sgn f32)
    (local.set $one (f32.const 1.0))
    (local.set $sgn (f32.copysign (local.get $one) (local.get $t)))
    (local.set $u (f32.abs (local.get $t)))
    (if (result f32)
      (f32.le (local.get $u) (f32.const 1.0))
      (then
        (f32.mul (local.get $sgn) (call $__atan_small (local.get $u)))
      )
      (else
        (f32.sub
          (f32.mul (local.get $sgn) (global.get $HALF_PI))
          (call $__atan_small (f32.div (f32.const 1.0) (local.get $u)))
        )
      )
    )
  )

  ;; ─── Tier 2 exports ────────────────────────────────────────────────────────
  ;; Fold xr from [-PI, PI] into [-HALF_PI, HALF_PI] so Taylor is accurate near ±PI
  (func $sin (export "sin") (param $x f32) (result f32)
    (local $t f32)
    (local $xr f32)
    (local.set $t (f32.add (local.get $x) (global.get $PI)))
    (local.set $t (f32.div (local.get $t) (global.get $TWO_PI)))
    (local.set $t (f32.floor (local.get $t)))
    (local.set $t (f32.mul (local.get $t) (global.get $TWO_PI)))
    (local.set $xr (f32.sub (local.get $x) (local.get $t)))
    (if (f32.gt (local.get $xr) (global.get $HALF_PI))
      (then (local.set $xr (f32.sub (global.get $PI) (local.get $xr))))
    )
    (if (f32.lt (local.get $xr) (f32.neg (global.get $HALF_PI)))
      (then (local.set $xr (f32.sub (f32.neg (global.get $PI)) (local.get $xr))))
    )
    (call $__sin_reduced (local.get $xr))
  )

  (func $cos (export "cos") (param $x f32) (result f32)
    (call $sin (f32.add (local.get $x) (global.get $HALF_PI)))
  )

  (func $tan (export "tan") (param $x f32) (result f32)
    (local $s f32)
    (local $c f32)
    (local.set $s (call $sin (local.get $x)))
    (local.set $c (call $cos (local.get $x)))
    (f32.div (local.get $s) (local.get $c))
  )

  (func $atan2 (export "atan2") (param $y f32) (param $x f32) (result f32)
    (local $a f32)
    (local $t f32)
    (if
      (i32.and
        (f32.eq (local.get $x) (f32.const 0))
        (f32.eq (local.get $y) (f32.const 0))
      )
      (then (return (f32.const 0)))
    )
    (if
      (f32.eq (local.get $x) (f32.const 0))
      (then (return (f32.copysign (global.get $HALF_PI) (local.get $y))))
    )
    (local.set $t (f32.div (local.get $y) (local.get $x)))
    (local.set $a (call $__atan_full (local.get $t)))
    (if
      (f32.lt (local.get $x) (f32.const 0))
      (then
        (if
          (f32.ge (local.get $y) (f32.const 0))
          (then (local.set $a (f32.add (local.get $a) (global.get $PI))))
          (else (local.set $a (f32.sub (local.get $a) (global.get $PI))))
        )
      )
    )
    (local.get $a)
  )

  (func $pow (export "pow") (param $base f32) (param $exp i32) (result f32)
    (local $r f32)
    (local $b f32)
    (local $e i32)
    (local $neg i32)
    (local.set $neg (i32.const 0))
    (if
      (i32.lt_s (local.get $exp) (i32.const 0))
      (then
        (local.set $neg (i32.const 1))
        (local.set $e (i32.sub (i32.const 0) (local.get $exp)))
      )
      (else (local.set $e (local.get $exp)))
    )
    (local.set $r (f32.const 1))
    (local.set $b (local.get $base))
    (block $done
      (loop $lp
        (if
          (i32.eqz (local.get $e))
          (then (br $done))
        )
        (if
          (i32.and (local.get $e) (i32.const 1))
          (then (local.set $r (f32.mul (local.get $r) (local.get $b))))
        )
        (local.set $b (f32.mul (local.get $b) (local.get $b)))
        (local.set $e (i32.shr_u (local.get $e) (i32.const 1)))
        (br $lp)
      )
    )
    (if
      (i32.eqz (local.get $neg))
      (then (return (local.get $r)))
    )
    (f32.div (f32.const 1.0) (local.get $r))
  )

  (func $fmod (export "fmod") (param $x f32) (param $y f32) (result f32)
    (local $q f32)
    (local.set $q (f32.trunc (f32.div (local.get $x) (local.get $y))))
    (f32.sub (local.get $x) (f32.mul (local.get $q) (local.get $y)))
  )

  ;; ─── Existing stdlib ───────────────────────────────────────────────────────
  (func $i_to_f (export "i_to_f") (param $i i32) (result f32)
    (return (f32.convert_i32_s (local.get $i)))
  )

  (func $min_i32 (export "min_i32") (param $a i32) (param $b i32) (result i32)
    (if
      (i32.lt_s (local.get $a) (local.get $b))
      (then (return (local.get $a)))
    )
    (return (local.get $b))
  )

  (func $min_f32 (export "min_f32") (param $a f32) (param $b f32) (result f32)
    (if
      (f32.lt (local.get $a) (local.get $b))
      (then (return (local.get $a)))
    )
    (return (local.get $b))
  )

  (func $max_i32 (export "max_i32") (param $a i32) (param $b i32) (result i32)
    (if
      (i32.lt_s (local.get $a) (local.get $b))
      (then (return (local.get $b)))
    )
    (return (local.get $a))
  )

  (func $max_f32 (export "max_f32") (param $a f32) (param $b f32) (result f32)
    (if
      (f32.lt (local.get $a) (local.get $b))
      (then (return (local.get $b)))
    )
    (return (local.get $a))
  )
)
